# scrutinizer-ci.com configuration
# language: python
imports:
- python

build:
  environment:
    python: 3.7.0
  tests:
    before:
    - 'python setup.py install'
    - 'pip install nose-exclude'
    override:
    - command: 'nosetests'
  nodes:

    analysis:
      tests:
        override:
        - py-scrutinizer-run

    coverage:
      tests:
        before:
        - 'python setup.py install'
        - 'pip install nose-exclude'
        override:
          - command: 'nosetests'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'