# scrutinizer-ci.com configuration
# language: python
imports:
    - python

build:
    environment:
        python: 3.6.3
    tests:
        before:
            - 'python setup.py install'
            - 'pip install nose-exclude'
        override:
            -
                command: 'nosetests'

checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true